version: '3'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: localhost
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/:/var/lib/rabbitmq
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"