version: "3.2"

services:
  test:
    image: docker:18.09.7
    command: ["docker", "info", "--format=NodeID: {{ json .Swarm.NodeID }}", "--format=Name: {{json .Name}}"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      mode: global
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=* * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
