version: '2.3'
services:
    #activemq容器
  activemq:
    #使用的镜像
    image: rmohr/activemq
    restart: always
    #容器的映射端口
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
    #定义挂载点
    # volumes:
      # - /etc/localtime:/etc/localtime:ro
      # - ./data/data/activemq:/data/activemq
      # - ./data/var/log/activemq:/var/log/activemq
    #环境变量
    environment:
      - TZ=Asia/Shanghai
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048