version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka_zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka_network
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_kafka
    ports: 
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      HOSTNAME_COMMAND: "ifconfig eth0 | grep 'inet addr' | awk '{ print $$2}' | awk -F: '{print $$2}'"
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka_network
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka_manager
    environment:
      ZK_HOSTS: zookeeper
    ports:
      - "9001:9000"
    networks:
      - kafka_network
networks:
  kafka_network:
    driver: overlay
    attachable: true