version: '3.7'
services:
  es:
    image: elasticsearch:6.7.2
    container_name: elasticsearch
    restart: always
    environment:
      # - node.name=es01
      # - cluster.name=tres
      - "discovery.type=single-node"
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config_copy:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
      - "9300:9300"
