version: '3.3'
services:
  zookeeper:
    image: zookeeper:3.7
    restart: always
    ports:
      - "2181:2181"
    networks:
      - zookeeper_network
    volumes:
      - ./data:/data
      - ./datalog:/datalog

networks:
  zookeeper_network:
    driver: overlay
    attachable: true