version: "3.1"

services:
  portainer:
    image: portainer/portainer-ce
    privileged: true
    restart: always
    container_name: "portainer"
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
