version: '3.3'
services:   
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
    - "3306:3306"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: "changyw"
      #MYSQL_USER: 'root'
      #MYSQL_PASS: 'changyw'
    volumes: 
    - ./data:/var/lib/mysql
    - ./conf/my.cnf:/etc/my.cnf
    restart: always
    networks:
      - mysql_net
    
networks:
  mysql_net:
    name: mysql_net
    driver: bridge