version: "3.3"

services:
  influxdb:
    image: influxdb
    restart: always
    container_name: "influxdb"
    # command: /usr/bin/influx
    networks:
      - db_network
    ports:
      - 8083:8083
      - 8086:8086
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
    volumes:
      - /docker/influxdb/conf/influxdb.conf:/etc/influxdb/influxdb.conf 
      - /docker/influxdb/data:/var/lib/influxdb/data 
      - /docker/influxdb/meta:/var/lib/influxdb/meta 
      - /docker/influxdb/wal:/var/lib/influxdb/wal
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      # - ADMIN_USER = "root"
      # - INFLUXDB_INIT_PWD = "root"
      # - PRE_CREATE_DB = "changtest"
      - INFLUXDB_ADMIN_ENABLED:"true"
networks:
  db_network:
    attachable: true
